[build-system]
requires = ["setuptools>=42.0", "wheel", "numpy", "pycuda"]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
addopts = "--cov=cuda_dip_modeller"
testpaths = [
    "tests",
]